name: 'ph-migration-custom-action'
description: 'POC PH Custom Action'
inputs:
  type: 
    description: 'Type of version upgrade'
    required: true
    default: 'patch'
inputs:
  old_version: 
    description: 'Previous version'
  new_version: 
    description: 'New version'
runs:
  using: 'node12'
  main: 'dist/index.js'